### PR TITLE
Added Sandbox Demo For MultiDropdownList

### PR DESCRIPTION
**Pull request by divyanshu-rawat**
Added Sandbox Demo For MultiDropdownList - https://codesandbox.io/s/m5wy51xv3p

### CODE REVIEW

**Comment by bietkul** [comment]
@divyanshu-rawat Please add SelectedFilters in all codesanbox demos.
And keep the same layout in full screen mode as we have in storybook demos( in this example suggestions list covers the results ).

**Comment by divyanshu-rawat** [comment]
@bietkul 
If I will try to have the storybook demos layout then in small screen where to put MultiDropdownList and result?

And for react one we also have the same layout - https://opensource.appbase.io/reactive-manual/list-components/singledropdownlist.html

**Comment by bietkul** [comment]
@divyanshu-rawat Right, keep the same for small screen but change it for large screens.
Check out the react example for larger screens https://z2kw0wx6mm.codesandbox.io/.

**Comment by divyanshu-rawat** [comment]
sure @bietkul 👍

**Comment by divyanshu-rawat** [comment]
@bietkul updated the sandbox kindly check it now 👍

**Pull request merged**
